// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DefaultConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=(local)\SQLEXPRESS;Initial Catalog=events-dev;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace events.dal.Models
{
    /// <summary>
    /// A class which represents the AspNetRoles table.
    /// </summary>
	[Table("AspNetRoles")]
	public partial class AspNetRole
	{
		[Key]
		public virtual string Id { get; set; }
		public virtual string ConcurrencyStamp { get; set; }
		public virtual string Name { get; set; }
		public virtual string NormalizedName { get; set; }
		public virtual IEnumerable<AspNetRoleClaim> AspNetRoleClaims { get; set; }
		public virtual IEnumerable<AspNetUserRole> AspNetUserRoles { get; set; }
	}

    /// <summary>
    /// A class which represents the AspNetUserTokens table.
    /// </summary>
	[Table("AspNetUserTokens")]
	public partial class AspNetUserToken
	{
		[Key]
		public virtual string UserId { get; set; }
		public virtual string LoginProvider { get; set; }
		public virtual string Name { get; set; }
		public virtual string Value { get; set; }
	}

    /// <summary>
    /// A class which represents the AspNetUsers table.
    /// </summary>
	[Table("AspNetUsers")]
	public partial class AspNetUser
	{
		[Key]
		public virtual string Id { get; set; }
		public virtual int AccessFailedCount { get; set; }
		public virtual string ConcurrencyStamp { get; set; }
		public virtual string Email { get; set; }
		public virtual bool EmailConfirmed { get; set; }
		public virtual bool LockoutEnabled { get; set; }
		public virtual string LockoutEnd { get; set; }
		public virtual string NormalizedEmail { get; set; }
		public virtual string NormalizedUserName { get; set; }
		public virtual string PasswordHash { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual bool PhoneNumberConfirmed { get; set; }
		public virtual string SecurityStamp { get; set; }
		public virtual bool TwoFactorEnabled { get; set; }
		public virtual string UserName { get; set; }
		public virtual IEnumerable<AspNetUserClaim> AspNetUserClaims { get; set; }
		public virtual IEnumerable<AspNetUserLogin> AspNetUserLogins { get; set; }
		public virtual IEnumerable<AspNetUserRole> AspNetUserRoles { get; set; }
	}

    /// <summary>
    /// A class which represents the Event table.
    /// </summary>
	[Table("Event")]
	public partial class Event
	{
		[Key]
		public virtual Guid Id { get; set; }
		public virtual string SourceUri { get; set; }
		public virtual string Uri { get; set; }
		public virtual string Name { get; set; }
		public virtual string Summary { get; set; }
		public virtual string Description { get; set; }
		public virtual string EventType { get; set; }
		public virtual string StartDate { get; set; }
		public virtual string EndDate { get; set; }
		public virtual string ImageUri { get; set; }
		public virtual string Performer { get; set; }
		public virtual string Offers { get; set; }
		public virtual string LocationUri { get; set; }
		public virtual string LocationName { get; set; }
		public virtual string Street { get; set; }
		public virtual string Zip { get; set; }
		public virtual string Locality { get; set; }
		public virtual string Region { get; set; }
		public virtual string Country { get; set; }
		public virtual decimal? Longitude { get; set; }
		public virtual decimal? Latitude { get; set; }
	}

    /// <summary>
    /// A class which represents the AspNetRoleClaims table.
    /// </summary>
	[Table("AspNetRoleClaims")]
	public partial class AspNetRoleClaim
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string ClaimType { get; set; }
		public virtual string ClaimValue { get; set; }
		public virtual string RoleId { get; set; }
		public virtual AspNetRole AspNetRole { get; set; }
	}

    /// <summary>
    /// A class which represents the AspNetUserClaims table.
    /// </summary>
	[Table("AspNetUserClaims")]
	public partial class AspNetUserClaim
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string ClaimType { get; set; }
		public virtual string ClaimValue { get; set; }
		public virtual string UserId { get; set; }
		public virtual AspNetUser AspNetUser { get; set; }
	}

    /// <summary>
    /// A class which represents the AspNetUserLogins table.
    /// </summary>
	[Table("AspNetUserLogins")]
	public partial class AspNetUserLogin
	{
		[Key]
		public virtual string LoginProvider { get; set; }
		public virtual string ProviderKey { get; set; }
		public virtual string ProviderDisplayName { get; set; }
		public virtual string UserId { get; set; }
		public virtual AspNetUser AspNetUser { get; set; }
	}

    /// <summary>
    /// A class which represents the AspNetUserRoles table.
    /// </summary>
	[Table("AspNetUserRoles")]
	public partial class AspNetUserRole
	{
		[Key]
		public virtual string UserId { get; set; }
		public virtual string RoleId { get; set; }
		public virtual AspNetUser AspNetUser { get; set; }
		public virtual AspNetRole AspNetRole { get; set; }
	}

}
